Add Test chaining support
mukut1994/MK94.Assert pull request #24
Opened 2022-02-12 19:54 UTC by mukut1994

2022-02-13 00:46 UTC, mithileshz requested changes

2022-02-13 00:46 UTC, mithileshz commented on MK94.Assert.NUnit.Test/ChainingTests.cs
> +        public void Step1()
TestCase1

2022-02-13 00:46 UTC, mithileshz commented on MK94.Assert.NUnit.Test/ChainingTests.cs
> +        public void Step2()
TestCase2

2022-02-13 00:46 UTC, mithileshz commented on MK94.Assert.NUnit.Test/ChainingTests.cs
> +        public void Step3()
TestCase3

2022-02-13 00:46 UTC, mithileshz commented on MK94.Assert.NUnit/TestChainExtensions.cs
> +Call {nameof(TestChainer.From)}(string, string) instead to set it manually.");
Could the (string, string) not be automated too? So we don't have to worry about updating this if the method signature changes?

2022-02-13 00:46 UTC, mithileshz commented on MK94.Assert/DiskAsserter.cs
>          public string MatchesRaw(string step, string rawData, string fileType = null, IDifferenceFormatter<string> formatter = null)
fileType parameter is still missing from the comments descriving the method above.

2022-02-13 00:46 UTC, mithileshz commented on MK94.Assert/Output/IFileOutput.cs
> +    	public interface IFileOutput
Indentation

2022-02-13 00:46 UTC, mithileshz commented on MK94.Assert/Output/ITestOutput.cs
> +    	public interface ITestOutput
indentation

2022-02-13 00:46 UTC, mithileshz commented on TestData/MK94.Assert.NUnit.Test.ChainingTests/PreventChainingMethodNonNUnit/Exception non test method
> +This does not seem to be an NUnit test method.
it not an `an` NUnit Test Method but a `a`

2022-02-13 00:46 UTC, mithileshz commented on TestData/MK94.Assert.NUnit.Test.ChainingTests/PreventChainingMethodNonNUnit/Exception non test method
> +Call From(string, string) instead to set it manually.
In the future might want to direct to documentation instead?

2022-02-13 18:15 UTC, mukut1994 commented on MK94.Assert.NUnit/TestChainExtensions.cs
> +Call {nameof(TestChainer.From)}(string, string) instead to set it manually.");
Not that I know of

2022-02-13 18:15 UTC, mukut1994 commented on MK94.Assert/DiskAsserter.cs
>          public string MatchesRaw(string step, string rawData, string fileType = null, IDifferenceFormatter<string> formatter = null)
Fixed

2022-02-13 18:16 UTC, mukut1994 commented on TestData/MK94.Assert.NUnit.Test.ChainingTests/PreventChainingMethodNonNUnit/Exception non test method
> +Call From(string, string) instead to set it manually.
Yea that's a good idea actually, I guess that's something to put in the backlog
Need to have the docs first after all

2022-02-16 10:26 UTC, mithileshz approved these changes

2022-02-16 10:27 UTC, merged