Docs
mukut1994/MK94.Assert pull request #30
Opened 2022-02-16 20:44 UTC by mukut1994

2022-02-16 20:45 UTC, mithileshz requested changes
Rejected

2022-02-17 09:27 UTC, mithileshz commented on README.md
> +Files are stored in a "TestData/{Class Name}/{Test Name}" pattern. (by default, this is overrideable)
By default, files are stored in..... (Configurable via [link to option configuration here])

2022-02-17 09:44 UTC, mukut1994 commented on README.md
> +Files are stored in a "TestData/{Class Name}/{Test Name}" pattern. (by default, this is overrideable)
Didn't add a link.
Link to code felt wrong and we don't have a seperate doc for file output.
Just expanded it into it's own section with some examples

2022-02-17 09:52 UTC, mithileshz approved these changes

2022-02-17 09:56 UTC, merged